MusicFolder = '/mnt/music/collection2'
DataFolder = '/var/lib/navidrome'
CacheFoler = '/var/lib/navidrome/cache'
Scanner.Enabled = 1
ScanSchedule = '@every 10m'

[[Transcoding]]
Name = "AIFF to MP3 (High Quality)"
TargetFormat = "mp3"
DefaultBitRate = "320"
Command = "ffmpeg -i %s -ab %bk -q:a 0 -v 0 -f mp3 -"
Formats = "aiff,aif"
