MusicFolder = '/mnt/music/collection2'
DataFolder = '/var/lib/navidrome'
CacheFolder = '/var/lib/navidrome/cache'
Scanner.Enabled = 1
ScanSchedule = '@every 10m'
EnableTranscodingConfig = false

[FFmpeg]
Path = "/usr/bin/ffmpeg"

# Transcoding configured via UI instead of config file
# Go to http://37.27.252.86/app/#/admin/transcoding to configure
